global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'mongodb'
    static_configs:
      - targets: ['10.128.0.9:9216']

  - job_name: 'mongo-express'
    static_configs:
      - targets: ['10.128.0.10:9100']
